mail:
  from: "noreply@example.com"
  to: "" # "you@example.com"
  subject-prefix: "[订阅]" # 邮件标题前缀
  via: "sendmail" # sendmail/smtp 邮件详情参考: https://github.com/benprew/pony
  smtp-options:
    address: "" # "smtp.yourserver.com"
    port: "" # "25"
    user_name: "" # "user"
    password: "" # "password"
    domain: "" # "localhost.localdomain"

proxy: "" # "https://127.0.0.1:8888"

# rule:       [必选] 规则文件名
# cron:       [必选] 定时任务 (写法同 crontab)
# proxy:      [可选] 是否使用代理 (true/false)
# param-name: [可选] 标题中的参数
# param-url:  [可选] URL中的参数
following:
  - rule: "ituring"
    cron: "0 10 * * *"
  - rule: "smzdm-tag-x"
    cron: "0 */3 * * *"
    param-name: "绝对值"
    param-url: "绝对值"
